### ISSUE TITLE
app crash on http://localhost:1338/profile

### ISSUE THREAD

**Issue by mlibre** [Ymple/ymple-ecommerce#121]
After login with admin@admin.com. and open http://localhost:1338/profile page.
app crash.
Full Log
```
 node app.js 
debug: The `config.views.engine` config has been deprecated.
debug: In Sails 1.x, use `config.views.extension` to choose your view
debug: extension (defaults to ".ejs"), and use `config.views.getRenderFn`
debug: to configure your template engine or leave it undefined to use
debug: the built-in EJS template support.

debug: The `sails.config.cors` config has been deprecated.
debug: Please use `sails.config.security.cors` instead.
debug: (we'll use your `sails.config.cors` settings for now).

sails.config.connections
sails.config.connections
sails.config.connections
sails.config.connections
 warn: Action middleware (POLICY: sessionadmin) was bound to a target `order/index` that doesn't match any registered actions.
 warn: Action middleware (POLICY: sessionadmin) was bound to a target `product/delete` that doesn't match any registered actions.
 warn: Action middleware (POLICY: sessionadmin) was bound to a target `product/status` that doesn't match any registered actions.
 warn: Action middleware (POLICY: sessionauth) was bound to a target `user/profile` that doesn't match any registered actions.

debug: -------------------------------------------------------
debug: :: Fri Mar 09 2018 22:10:54 GMT+0330 (+0330)
debug: Environment : development
debug: Port        : 1338
debug: -------------------------------------------------------
UserController - loginStep1 {}
UserController - login
UserController - login - user { name: 'admin',
  email: 'admin@admin.com',
  password: '$2a$10$odRQlMoI7gfQsw96ZcLKYOAuMabM3/OwACHIOjsf6hnskiJ/wuZAS',
  permission: 'ADMIN',
  createdAt: '2018-03-09T18:04:52.548Z',
  updatedAt: '',
  id: '5aa2ccc40a5e8e476b8d9c44' }
redirect_url { redirect_url: '/' }
new products []
productController products []
getListCoreModule - data []
promise return value categoryList: []
debug: ***********************************************************************************
debug: `res.jsonx()` is deprecated in Sails v1.0 and will be removed in a future release.
debug: Any files in `api/responses/` that haven't been customized can simply be removed.
debug: Otherwise see http://sailsjs.com/upgrading for options to replace `res.jsonx()`.
debug: (jsonx was called from `notFound`)
debug: ***********************************************************************************
user id  5aa2ccc40a5e8e476b8d9c44
/home/mlibre/healoba_shop/node_modules/sails-mongo/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                  ^

Error: Encountered unexpected error while building join instructions for `.populate("orders")`
Details:
Error: In `.populate("orders")`, attempting to populate an attribute that doesn't exist
    at module.exports.Deferred.populate (/home/mlibre/healoba_shop/node_modules/waterline/lib/waterline/query/deferred.js:146:13)
    at GetUserAndOrders (/home/mlibre/healoba_shop/api/controllers/core/front/UserController.js:80:51)
    at nextTask (/home/mlibre/healoba_shop/node_modules/async/dist/async.js:5310:14)
    at next (/home/mlibre/healoba_shop/node_modules/async/dist/async.js:5317:9)
    at /home/mlibre/healoba_shop/node_modules/async/dist/async.js:958:16
    at /home/mlibre/healoba_shop/api/controllers/core/front/UserController.js:71:28
    at wrapper (/home/mlibre/healoba_shop/node_modules/waterline/node_modules/lodash/index.js:3592:19)
    at applyInOriginalCtx (/home/mlibre/healoba_shop/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/home/mlibre/healoba_shop/node_modules/waterline/lib/waterline/utils/normalize.js:324:18)
    at success (/home/mlibre/healoba_shop/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/home/mlibre/healoba_shop/node_modules/waterline/node_modules/switchback/lib/factory.js:58:28)
    at /home/mlibre/healoba_shop/node_modules/sails-mongo/lib/adapter.js:430:9
    at /home/mlibre/healoba_shop/node_modules/sails-mongo/lib/collection.js:324:5
    at handleCallback (/home/mlibre/healoba_shop/node_modules/sails-mongo/node_modules/mongodb/lib/utils.js:95:56)
    at /home/mlibre/healoba_shop/node_modules/sails-mongo/node_modules/mongodb/lib/collection.js:2052:5
    at handleCallback (/home/mlibre/healoba_shop/node_modules/sails-mongo/node_modules/mongodb/lib/utils.js:95:56)
    at /home/mlibre/healoba_shop/node_modules/sails-mongo/node_modules/mongodb/lib/db.js:313:5
    at /home/mlibre/healoba_shop/node_modules/sails-mongo/node_modules/mongodb-core/lib/connection/pool.js:455:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at module.exports.Deferred.populate (/home/mlibre/healoba_shop/node_modules/waterline/lib/waterline/query/deferred.js:264:11)
    at GetUserAndOrders (/home/mlibre/healoba_shop/api/controllers/core/front/UserController.js:80:51)
    at nextTask (/home/mlibre/healoba_shop/node_modules/async/dist/async.js:5310:14)
    at next (/home/mlibre/healoba_shop/node_modules/async/dist/async.js:5317:9)
    at /home/mlibre/healoba_shop/node_modules/async/dist/async.js:958:16
    at /home/mlibre/healoba_shop/api/controllers/core/front/UserController.js:71:28
    at wrapper (/home/mlibre/healoba_shop/node_modules/waterline/node_modules/lodash/index.js:3592:19)
    at applyInOriginalCtx (/home/mlibre/healoba_shop/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/home/mlibre/healoba_shop/node_modules/waterline/lib/waterline/utils/normalize.js:324:18)
    at success (/home/mlibre/healoba_shop/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/home/mlibre/healoba_shop/node_modules/waterline/node_modules/switchback/lib/factory.js:58:28)
    at /home/mlibre/healoba_shop/node_modules/sails-mongo/lib/adapter.js:430:9
    at /home/mlibre/healoba_shop/node_modules/sails-mongo/lib/collection.js:324:5
    at handleCallback (/home/mlibre/healoba_shop/node_modules/sails-mongo/node_modules/mongodb/lib/utils.js:95:56)
    at /home/mlibre/healoba_shop/node_modules/sails-mongo/node_modules/mongodb/lib/collection.js:2052:5
    at handleCallback (/home/mlibre/healoba_shop/node_modules/sails-mongo/node_modules/mongodb/lib/utils.js:95:56)
    at /home/mlibre/healoba_shop/node_modules/sails-mongo/node_modules/mongodb/lib/db.js:313:5
    at /home/mlibre/healoba_shop/node_modules/sails-mongo/node_modules/mongodb-core/lib/connection/pool.js:455:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by Rob-Rychs** [comment]
Hey you've created and running a mongo db instance on default port?

**Comment by fabienthetis** [comment]
Seems that you need first to go to this url after a fresh installation: 
http://localhost:1338/install
Yes, default port : 27017
